export const gangs: { [key: string]: string } = {
  lost: 'The Lost',
  angels: 'Angels of Death',
  'santa muerte': 'La Santa Muerte',
  insanos: 'Insanos',
  infamous: 'Infamous',
  ballas: 'Ballas',
  hustlers: 'Hustlers',
  'black rose': 'Black Rose',
  cesarini: 'Cesarini',
  madrazo: 'Madrazo',
  vitale: 'Vitale',
  saints: 'Saints',
  sharkSix: 'Shark Six',
  anarquia: 'Anarquia',
  roots: 'Roots Crew',
  stl: 'STL',
  mib: 'MIB',
  bandoleros: 'Bandoleros',
  forgotten: 'Forgotten',
}
