export const gangs: { [key: string]: string } = {
  lost: 'The Lost',
  angels: 'Angels of Death',
  'santa muerte': 'La Santa Muerte',
  insanos: 'Insanos',
  ballas: 'Ballas',
  hustlers: 'Hustlers',
  'black rose': 'Black Rose',
  cesarini: 'Cesarini',
  families: 'Families',
  anarquia: 'Anarquia',
  stl: 'STL',
  mib: 'MIB',
  bandoleros: 'Bandoleros',
  forgotten: 'Forgotten',
  sharks: 'Shark Six',
  bsg: 'BSG',
}
